import { useEffect, useState, type FormEvent } from 'react';
import { api, formatDateTime } from '../api';
import type { AttendanceEventType, AttendanceRow, Employee } from '../types';
import Modal from '../components/Modal';

export default function AttendancePage() {
  const [rows, setRows] = useState<AttendanceRow[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [modal, setModal] = useState(false); const [employeeId, setEmployeeId] = useState(''); const [type, setType] = useState<AttendanceEventType>('CheckIn'); const [occurredAt, setOccurredAt] = useState(() => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset()*60000).toISOString().slice(0,16); }); const [note, setNote] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [a,e] = await Promise.all([api<AttendanceRow[]>('/api/attendance'), api<Employee[]>('/api/employees')]); setRows(a); setEmployees(e); if (!employeeId && e[0]) setEmployeeId(e[0].id); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Hiba'); } };
  useEffect(() => { void load(); }, []);
  async function save(e: FormEvent) { e.preventDefault(); try { await api('/api/attendance/manual', { method:'POST', body:JSON.stringify({employeeId,type,occurredAt:new Date(occurredAt).toISOString(),note:note || null})}); setModal(false); setNote(''); await load(); } catch(e){ setError(e instanceof Error ? e.message : 'Mentési hiba'); } }
  return <section><div className="page-header"><div><p className="eyebrow">Események</p><h1>Jelenléti napló</h1><p>A terminálos és kézzel rögzített események egy helyen.</p></div><button className="primary-button" onClick={() => setModal(true)}>+ Kézi bejegyzés</button></div>{error && <div className="alert error">{error}</div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Időpont</th><th>Dolgozó</th><th>Esemény</th><th>Forrás</th><th>Terminál</th><th>Megjegyzés</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="empty">Nincs jelenléti esemény.</td></tr>:rows.map(x=><tr key={x.id}><td>{formatDateTime(x.occurredAtUtc)}</td><td><strong>{x.employeeName}</strong></td><td><span className={x.type==='CheckIn'?'event-in':'event-out'}>{x.type==='CheckIn'?'BE':'KI'}</span></td><td>{x.source==='Terminal'?'Terminál':'Admin'}</td><td>{x.terminalName ?? '—'}</td><td>{x.note ?? '—'}</td></tr>)}</tbody></table></div></div>{modal&&<Modal title="Kézi jelenléti bejegyzés" onClose={()=>setModal(false)}><form className="form-grid" onSubmit={save}><label>Dolgozó<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required>{employees.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select></label><label>Esemény<select value={type} onChange={e=>setType(e.target.value as AttendanceEventType)}><option value="CheckIn">Bejelentkezés</option><option value="CheckOut">Kijelentkezés</option></select></label><label>Időpont<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)} required /></label><label>Megjegyzés<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={()=>setModal(false)}>Mégse</button><button className="primary-button">Rögzítés</button></div></form></Modal>}</section>;
}
