import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import type { Employee } from '../types';
import Modal from '../components/Modal';

type FormState = { id?: string; employeeCode: string; fullName: string; dailyTargetMinutes: number; isActive: boolean };
const empty: FormState = { employeeCode: '', fullName: '', dailyTargetMinutes: 480, isActive: true };

export default function EmployeesPage() {
  const [rows, setRows] = useState<Employee[]>([]); const [form, setForm] = useState<FormState | null>(null); const [rfidFor, setRfidFor] = useState<Employee | null>(null); const [rfid, setRfid] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { setRows(await api<Employee[]>('/api/employees')); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Hiba'); } };
  useEffect(() => { void load(); }, []);

  async function save(e: FormEvent) { e.preventDefault(); if (!form) return; try { const url = form.id ? `/api/employees/${form.id}` : '/api/employees'; await api(url, { method: form.id ? 'PUT' : 'POST', body: JSON.stringify(form) }); setForm(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Mentési hiba'); } }
  async function saveRfid(e: FormEvent) { e.preventDefault(); if (!rfidFor) return; try { await api(`/api/employees/${rfidFor.id}/rfid`, { method: 'PUT', body: JSON.stringify({ rfidUid: rfid }) }); setRfidFor(null); setRfid(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'RFID mentési hiba'); } }

  return <section><div className="page-header"><div><p className="eyebrow">Törzsadatok</p><h1>Dolgozók</h1><p>Dolgozói adatok, munkaidőkeret és RFID kártyák kezelése.</p></div><button className="primary-button" onClick={() => setForm({ ...empty })}>+ Új dolgozó</button></div>{error && <div className="alert error">{error}</div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Kód</th><th>Név</th><th>RFID</th><th>Napi cél</th><th>Állapot</th><th></th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={6} className="empty">Még nincs dolgozó.</td></tr> : rows.map(x => <tr key={x.id}><td><span className="mono">{x.employeeCode}</span></td><td><strong>{x.fullName}</strong></td><td>{x.rfidUid ? <span className="mono badge">{x.rfidUid}</span> : <span className="muted">nincs kártya</span>}</td><td>{Math.floor(x.dailyTargetMinutes/60)} ó {x.dailyTargetMinutes%60} p</td><td><span className={x.isActive ? 'status present' : 'status away'}>{x.isActive ? 'Aktív' : 'Inaktív'}</span></td><td className="actions"><button className="small-button" onClick={() => { setRfidFor(x); setRfid(x.rfidUid ?? ''); }}>RFID</button><button className="small-button" onClick={() => setForm({ id:x.id, employeeCode:x.employeeCode, fullName:x.fullName, dailyTargetMinutes:x.dailyTargetMinutes, isActive:x.isActive })}>Szerkesztés</button></td></tr>)}</tbody></table></div></div>{form && <Modal title={form.id ? 'Dolgozó szerkesztése' : 'Új dolgozó'} onClose={() => setForm(null)}><form className="form-grid" onSubmit={save}><label>Dolgozói kód<input value={form.employeeCode} onChange={e => setForm({...form, employeeCode:e.target.value})} required /></label><label>Teljes név<input value={form.fullName} onChange={e => setForm({...form, fullName:e.target.value})} required /></label><label>Napi elvárt perc<input type="number" min="0" max="1440" value={form.dailyTargetMinutes} onChange={e => setForm({...form, dailyTargetMinutes:Number(e.target.value)})} required /></label><label className="check-label"><input type="checkbox" checked={form.isActive} onChange={e => setForm({...form,isActive:e.target.checked})}/> Aktív dolgozó</label><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setForm(null)}>Mégse</button><button className="primary-button">Mentés</button></div></form></Modal>}{rfidFor && <Modal title={`RFID – ${rfidFor.fullName}`} onClose={() => setRfidFor(null)}><form onSubmit={saveRfid}><p className="modal-help">Add meg a kártya UID-ját. A terminál-integráció következő lépésében ezt közvetlenül csippantással is hozzá tudjuk majd rendelni.</p><label>RFID UID<input className="mono" value={rfid} onChange={e => setRfid(e.target.value)} placeholder="04A793218F" required /></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setRfidFor(null)}>Mégse</button><button className="primary-button">Kártya mentése</button></div></form></Modal>}</section>;
}
