import { useEffect, useState, type FormEvent } from 'react';
import { api, formatDateTime } from '../api';
import type { Terminal } from '../types';
import Modal from '../components/Modal';

export default function TerminalsPage() {
  const [rows,setRows]=useState<Terminal[]>([]); const [modal,setModal]=useState(false); const [deviceId,setDeviceId]=useState(''); const [name,setName]=useState(''); const [newKey,setNewKey]=useState<{deviceId:string;apiKey:string}|null>(null); const [error,setError]=useState('');
  const load=async()=>{try{setRows(await api<Terminal[]>('/api/terminals'));setError('');}catch(e){setError(e instanceof Error?e.message:'Hiba');}};
  useEffect(()=>{void load();},[]);
  async function save(e:FormEvent){e.preventDefault();try{const result=await api<{deviceId:string;apiKey:string}>('/api/terminals',{method:'POST',body:JSON.stringify({deviceId,name})});setModal(false);setDeviceId('');setName('');setNewKey(result);await load();}catch(e){setError(e instanceof Error?e.message:'Mentési hiba');}}
  async function regenerate(x:Terminal){try{const result=await api<{apiKey:string}>(`/api/terminals/${x.id}/regenerate-key`,{method:'POST'});setNewKey({deviceId:x.deviceId,apiKey:result.apiKey});}catch(e){setError(e instanceof Error?e.message:'Kulcsgenerálási hiba');}}
  return <section><div className="page-header"><div><p className="eyebrow">Hardver</p><h1>Terminálok</h1><p>M5Stack és későbbi beléptető eszközök hitelesítése.</p></div><button className="primary-button" onClick={()=>setModal(true)}>+ Új terminál</button></div>{error&&<div className="alert error">{error}</div>}{newKey&&<div className="secret-card"><div><strong>Új eszközkulcs – {newKey.deviceId}</strong><p>Ezt a kulcsot csak most mutatjuk. Mentsd el a terminál konfigurációjához.</p></div><code>{newKey.apiKey}</code><button className="small-button" onClick={()=>navigator.clipboard.writeText(newKey.apiKey)}>Másolás</button><button className="icon-button" onClick={()=>setNewKey(null)}>×</button></div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Device ID</th><th>Név</th><th>Utolsó kapcsolat</th><th>Állapot</th><th></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Még nincs terminál.</td></tr>:rows.map(x=><tr key={x.id}><td><span className="mono badge">{x.deviceId}</span></td><td><strong>{x.name}</strong></td><td>{formatDateTime(x.lastSeenAtUtc)}</td><td><span className={x.isActive?'status present':'status away'}>{x.isActive?'Aktív':'Inaktív'}</span></td><td className="actions"><button className="small-button" onClick={()=>regenerate(x)}>Új kulcs</button></td></tr>)}</tbody></table></div></div>{modal&&<Modal title="Új terminál" onClose={()=>setModal(false)}><form className="form-grid" onSubmit={save}><label>Device ID<input className="mono" value={deviceId} onChange={e=>setDeviceId(e.target.value)} placeholder="PETRIK-CLEAN-01" required/></label><label>Megjelenő név<input value={name} onChange={e=>setName(e.target.value)} placeholder="Főbejárat" required/></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={()=>setModal(false)}>Mégse</button><button className="primary-button">Létrehozás</button></div></form></Modal>}</section>;
}
